In [2]:
import pandas as pd
import numpy as np

In [3]:
bet_mgm_df = pd.read_csv('data/bet_mgm_mlb.csv')
caesars_df = pd.read_csv('data/caesars_mlb.csv')
draft_kings_df = pd.read_csv('data/draft_kings_mlb.csv')
events_df = pd.read_csv('data/events_mlb.csv')

In [4]:
sportsbooks = [(bet_mgm_df, 'Bet MGM'), (caesars_df, 'Caesars'), (draft_kings_df, 'Draft Kings')]

In [5]:
bet_mgm_df.head(6)

,Team,Spread,Total,Moneyline,Event ID
0,Mets,+1.5 -165,O 3.5 -105,325,f96334b1-c191-4b1e-9fdc-45e98ca1052f
1,Braves,-1.5 +130,U 3.5 -120,-450,f96334b1-c191-4b1e-9fdc-45e98ca1052f
2,Tigers,+1.5 -200,O 6.5 -105,120,98f468d9-4b42-4eb5-97ed-88346e109f11
3,Astros,-1.5 +165,U 6.5 -115,-145,98f468d9-4b42-4eb5-97ed-88346e109f11
4,Royals,+1.5 -190,O 7 +100,125,3ca66983-5de7-4c30-8439-683c930f584e
5,Orioles,-1.5 +155,U 7 -120,-150,3ca66983-5de7-4c30-8439-683c930f584e

In [6]:
caesars_df.head(6)

      Team    Spread    Total  Moneyline                              Event ID
0     Mets  +1.5-140  3.5+100        320  f96334b1-c191-4b1e-9fdc-45e98ca1052f
1   Braves  -1.5+110  3.5-130       -450  f96334b1-c191-4b1e-9fdc-45e98ca1052f
2   Tigers  +1.5-195  6.5+100        122  98f468d9-4b42-4eb5-97ed-88346e109f11
3   Astros  -1.5+162  6.5-120       -145  98f468d9-4b42-4eb5-97ed-88346e109f11
4   Royals  +1.5-178  7.0+105        130  3ca66983-5de7-4c30-8439-683c930f584e
5  Orioles  -1.5+150  7.0-125       -155  3ca66983-5de7-4c30-8439-683c930f584e

In [7]:
draft_kings_df.head(6)

,Team,Spread,Total,Moneyline,Event ID
0,Mets,+1.5−110,O 3.5−140,+390,f96334b1-c191-4b1e-9fdc-45e98ca1052f
1,Braves,-1.5−120,U 3.5+110,−600,f96334b1-c191-4b1e-9fdc-45e98ca1052f
2,Tigers,+1.5−192,O 6.5−102,+124,98f468d9-4b42-4eb5-97ed-88346e109f11
3,Astros,-1.5+160,U 6.5−118,−148,98f468d9-4b42-4eb5-97ed-88346e109f11
4,Royals,+1.5−180,O 7+100,+130,3ca66983-5de7-4c30-8439-683c930f584e
5,Orioles,-1.5+150,U 7−120,−155,3ca66983-5de7-4c30-8439-683c930f584e

In [8]:
events_df

                               Event ID Team One Team Two
0  f96334b1-c191-4b1e-9fdc-45e98ca1052f     Mets   Braves
1  98f468d9-4b42-4eb5-97ed-88346e109f11   Tigers   Astros
2  3ca66983-5de7-4c30-8439-683c930f584e   Royals  Orioles

In [9]:
def clean_moneyline(ml_value):
	if isinstance(ml_value, str):
		ml_value = ml_value.replace('−', '-').replace('+', '')  # Clean up special minus or plus signs
	return int(ml_value)  # Convert to integer

def implied_probability(moneyline):
	if moneyline < 0:
		return -moneyline / (-moneyline + 100)
	else:
		return 100 / (moneyline + 100)

def check_arbitrage(team_one_ml, team_two_ml):
	# Get the lowest implied probabilities for both teams
	best_team_one_prob = min([implied_probability(ml) for ml, book in team_one_ml])
	best_team_two_prob = min([implied_probability(ml) for ml, book in team_two_ml])
	
	# Sum the best probabilities
	total_implied_prob = best_team_one_prob + best_team_two_prob
	
	# Check for arbitrage
	if total_implied_prob < 1:
		print("Arbitrage opportunity exists!", total_implied_prob)
	else:
		print("No arbitrage opportunity.", total_implied_prob)

In [10]:
def has_arbitrage(event_id):
    row = events_df[events_df['Event ID'] == event_id]
    team_one = row['Team One'].item()
    team_two = row['Team Two'].item()
    
    print(team_one, team_two)

    team_one_ml = []
    team_two_ml = []
    
    for book, book_name in sportsbooks:
        team_one_ml_raw = book[(book['Event ID'] == event_id) & (book['Team'] == team_one)]['Moneyline']
        team_two_ml_raw = book[(book['Event ID'] == event_id) & (book['Team'] == team_two)]['Moneyline']

        if not team_one_ml_raw.empty and not pd.isna(team_one_ml_raw.item()):
            team_one_ml.append((clean_moneyline(team_one_ml_raw.item()), book_name))
        if not team_two_ml_raw.empty and not pd.isna(team_two_ml_raw.item()):
            team_two_ml.append((clean_moneyline(team_two_ml_raw.item()), book_name))
    
    check_arbitrage(team_one_ml, team_two_ml)

In [11]:
for index, event in events_df.iterrows():
	event_id = event['Event ID']
	# team_one = event['Team One']
	# team_two = event['Team Two']
	has_arbitrage(event_id)

Mets Braves
No arbitrage opportunity. 1.0222634508348794
Tigers Astros
No arbitrage opportunity. 1.038265306122449
Royals Orioles
No arbitrage opportunity. 1.0347826086956522

In [14]:
numbers = [x * x for x in range(1000000)]
# Generator: Only one element is yielded at a time
numbers_gen = (x * x for x in range(1000000))